/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3eva2exa;

/**
 *
 * @author Jonas
 */
import javax.swing.*;
import java.awt.*;
import java.io.*; 
public class Adivinalo extends javax.swing.JFrame {
    String Nombre,noml;
    int numero=555;
    int n,numl,c,mejor=0,peor=0,lon,a=0,i=0,longi=0,x=0,lng=0;
    int intentos=0;
    char aux;
     DataOutputStream fs=null;
     DataInputStream fe=null;
     String[] v=new String[10000];
    
    

    /**
     * Creates new form Adivinalo
     */
    public Adivinalo() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        t1.setColumns(30);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.setColumns(10);
        t2.setEnabled(false);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        nom.setText("Nombre");

        num.setText("acierta el numero");

        b1.setText("Terminar");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nom))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(num)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b1)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num))
                .addGap(43, 43, 43)
                .addComponent(b1)
                .addGap(32, 32, 32))
        );

        t2.getAccessibleContext().setAccessibleParent(t1);

        getAccessibleContext().setAccessibleParent(t1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
       Nombre=t1.getText();
       //nm=true; 
       //t2.setEditable(false);
       
   
       if (Nombre.length()==0)
       {
JOptionPane.showMessageDialog(null,"Debe introducir un nombre","Atencion",JOptionPane.ERROR_MESSAGE);		
       }
       
       else
       {    
           lng=Nombre.length()+1;
           for (x=lng;x<=10;x++)
           {
               Nombre=Nombre+"0";
           } 
           
           x=0;
           t2.setEnabled(true);
           t1.setEnabled(false);
           //t2.enableInputMethods(rootPaneCheckingEnabled);
           //t2.isEnabled();
           //t2.setEditable(true);
       }
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
       n=Integer.parseInt(t2.getText());
       
       
       if (n>0 && n<10000)
       {    
           intentos++;
       if(n<numero)
             num.setText("Mas Alto!");
       
       if(n>numero)
             num.setText("Mas Bajo!");
       
       if(n==numero)
        {
             num.setText("Acertaste!");
           try
		{
                fe = new DataInputStream(new BufferedInputStream(new FileInputStream("c:\\jugadores.txt"))); 
		fs = new DataOutputStream(new BufferedOutputStream(new FileOutputStream("c:\\jugadores.txt")));
                
              
                /* fs.writeUTF(Nombre);
		fs.writeInt(n); */
                v[a]=Nombre;
                v[a+1]=String.valueOf (intentos); 
                a=a+2;                               
		}	
		catch(Exception e){}	
		 /* finally
		{
			try
			{
				if(fs!=null)	
                                    fs.close();	
			}
			catch(IOException e){}		
		} */
        if (intentos<mejor||mejor==0)
        {
 JOptionPane.showMessageDialog(null,"Eres el mejor","Informacion",JOptionPane.ERROR_MESSAGE);
mejor=intentos;
intentos=0;
        }
        if (intentos>mejor&&intentos>peor)
        {
JOptionPane.showMessageDialog(null,"vaya,no has tenido mucha suerte","Informacion",JOptionPane.ERROR_MESSAGE);
peor=intentos;
        }
                intentos=0;
                t2.setEnabled(false);
                t1.setEnabled(true);
                num.setText("Acierta el numero");
       }
       }
       else
           num.setText("numero no valido");
           
        
    }//GEN-LAST:event_t2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
        try
		{		
                for (i=0;i<v.length;i++)
                    {  
                     fs.writeUTF(v[i]);
                     fs.writeInt(Integer.parseInt(v[i+1]));   
                     i++;
                    } 
		}	
		catch(Exception e){}	
		 finally
		{
			try
			{
				if(fs!=null)	
					fs.close();	
			}
			catch(IOException e){}		
		} 
       

    }//GEN-LAST:event_b1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
           

            public void run() {
                new Adivinalo().setVisible(true);
                 
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel num;
    public javax.swing.JTextField t1;
    public javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
