/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3eva2exa;

import javax.swing.*;
import java.awt.*;
import java.io.*;


/**
 *
 * @author Jonas
 */
public class Adivina extends javax.swing.JPanel {
    
    String Nombre,noml;
    int numero=555;
    int n,numl,c,mejor=0,peor=0,lon,a=0,i=0;
    int intentos=0;
     DataOutputStream fs=null;
     DataInputStream fe=null;
     String[] v=new String[10000];
    /**
     * Creates new form Adivina
     */
    public Adivina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        num = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        t1.setColumns(30);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        Nom.setText("Nombre");

        t2.setColumns(5);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        num.setText("Numero");

        b1.setText("Terminar");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Nom)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(num)
                        .addGap(69, 69, 69)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num))
                .addGap(40, 40, 40)
                .addComponent(b1)
                .addGap(48, 48, 48))
        );

        t2.getAccessibleContext().setAccessibleParent(t1);
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        Nombre=t1.getText();
       //nm=true; 
       //t2.setEditable(false);
       
   
       if (Nombre.length()==0)
       {
JOptionPane.showMessageDialog(null,"Debe introducir un nombre","Atencion",JOptionPane.ERROR_MESSAGE);		
       }
       
       else
       {
           t2.setEnabled(true);
           t1.setEnabled(false);
           //t2.enableInputMethods(rootPaneCheckingEnabled);
           //t2.isEnabled();
           //t2.setEditable(true);
       }
                                      

        
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        n=Integer.parseInt(t2.getText());
       
       
       if (n>0 && n<10000)
       {    
           intentos++;
       if(n<numero)
             num.setText("Mas Alto!");
       
       if(n>numero)
             num.setText("Mas Bajo!");
       
       if(n==numero)
        {
             num.setText("Acertaste!");
           try
		{		
		fs = new DataOutputStream(new BufferedOutputStream(new FileOutputStream("c:\\jugadores.txt")));
                fe = new DataInputStream(new BufferedInputStream(new FileInputStream("c:\\jugadores.txt"))); 
              
                /* fs.writeUTF(Nombre);
		fs.writeInt(n); */
                v[a]=Nombre;
                v[a+1]=String.valueOf (intentos); 
                a=a+2;                               
		}	
		catch(Exception e){}	
		 /* finally
		{
			try
			{
				if(fs!=null)	
                                    fs.close();	
			}
			catch(IOException e){}		
		} */
        if (intentos<mejor||mejor==0)
        {
 JOptionPane.showMessageDialog(null,"Eres el mejor","Informacion",JOptionPane.ERROR_MESSAGE);
mejor=intentos;
intentos=0;
        }
        if (intentos>mejor&&intentos>peor)
        {
JOptionPane.showMessageDialog(null,"vaya,no has tenido mucha suerte","Informacion",JOptionPane.ERROR_MESSAGE);
peor=intentos;
        }
                intentos=0;
                t2.setEnabled(false);
                t1.setEnabled(true);
                num.setText("Acierta el numero");
       }
       }
       else
           num.setText("numero no valido");
           
        
    
    }//GEN-LAST:event_t2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try
		{		
                for (i=0;i<v.length;i++)
                    {  
                     fs.writeUTF(v[i]);
                     fs.writeInt(Integer.parseInt(v[i+1]));   
                     i++;
                    } 
		}	
		catch(Exception e){}	
		 finally
		{
			try
			{
				if(fs!=null)	
					fs.close();	
			}
			catch(IOException e){}		
		} 
    }//GEN-LAST:event_b1ActionPerformed


    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
           

            public void run() {
                new Adivina().setVisible(true);
                 
            }
        });
        
            
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nom;
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel num;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
